### ISSUE TITLE
Permalinks/Views

### ISSUE THREAD

**Issue by lfkeitel** [onesimus-systems/dandelion#24]
Create a system to allow permalinks for a particular search. Or maybe a views system per user to save frequent searches.

**Comment by dragonrider23** [comment]
Permalinks for logs was added in commit f7c5b5cdc4b3ba584ec1528b563915c40f4b4a77.

**Comment by lfkeitel** [comment]
We don't really have a need for search permalinks. If it comes up in the future, perhaps it'll be added then.
