### ISSUE TITLE
Drop support for PHP 5.4

### ISSUE THREAD

**Issue by lfkeitel** [onesimus-systems/dandelion#31]
PHP 5.4 is end of life leaving 5.5 and 5.6 as the current supported versions. Thus it is proposed to drop active support for PHP 5.4. There aren't too many new features in 5.5 that would probably be utilized, and for a while Dandelion may still work just fine in 5.4. But, in order to ensure a secure installation, 5.4 should be dropped from the active supported versions list.

This would affect Dandelion 6.1.0+.

**Comment by dragonrider23** [comment]
This will take affect starting with Dandelion 7.

**Comment by lfkeitel** [comment]
5.4 and 5.5 are officially EOL. 5.6 is now in security fixes only. Dandelion is verified to work correctly on PHP 7 so it may be beneficial to bump up the required version to 7.0+. This would allow Dandelion to take advantage of lots of new features including removing the shim for the password_* functions, type hinting, null coalescing operator, grouped `use` statements, and lot of other stuff. Although technically this would be warrant a major version bump, the major version will remain at 6 with release notes emphasizing the new requirement. The older PHP versions will still work for a little while until new development happens that uses the new features.

**Comment by lfkeitel** [comment]
Beginning with version 6.2.0, PHP 7.0 is the minimum for application operation.
